# Generated by Django 4.2.7 on 2023-11-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emply_id',
        ),
    ]
